name: my first github action yaml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from repo
        uses: action/checkout@v4

      - name: say hello github action
        run: echo "Hello from GitHub Action"
